TtsEngine: Prevent crash due to improper configuration
Log:
FATAL EXCEPTION: main
Process: com.android.settings, PID: 15043
java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=1977, result=1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4399)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4441)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6723)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.speech.tts.TtsEngines.parseEnginePrefFromList(TtsEngines.java:503)
	at android.speech.tts.TtsEngines.isLocaleSetToDefaultForEngine(TtsEngines.java:367)
	at com.android.settings.tts.TextToSpeechSettings.updateDefaultLocalePref(TextToSpeechSettings.java:502)
	at com.android.settings.tts.TextToSpeechSettings.onActivityResult(TextToSpeechSettings.java:485)
	at android.app.Activity.dispatchActivityResult(Activity.java:7489)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4392)
	... 11 more

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>