Fix test framework to allow Mockito tests to run successfully on ART.
Currently, Mockito tests don't run on ART (KitKat & L) due to an extra
NoClassDefFoundError exception being thrown while trying to resolve
internal test runner classes. These exceptions are benign, Mockito's
internal test runners all inherit from org.junit.runner.Runner, which is
not included in the setup, but none of them are actually used in tests.

The same apks succeed on Dalvik, and logcat shows the same exceptions
 going by, minus the NCDFE's.

Section 5.3 of the VM spec says the virtual machine has to wrap a
ClassNotFoundException in NoClassDefFoundError if the first exception
arises from verification or resolution but not initialization of that
particular class.

Bug: 17042833
Change-Id: I3af20f6884d9fa3afc3fbf9fcb238be10267827a