Close audio source after getting callback from HotwordDetectionService
Due to the file descriptor of audio source was closed before
the attempt to parcel the file descriptor when passing the
file descriptor to the HotwordDetectionService.

It will cause the exception below:
java.lang.RuntimeException: Bad file descriptor

It would be better to close audio source when getting
callback from HotwordDetectionService

Bug: 185569471
Test: atest CtsVoiceInteractionTestCases
Test: atest CtsVoiceInteractionTestCases --instant
Change-Id: I10774fd29d559b5d2bedc21b0ebb2ef849a1b7c6