Rename SearchableInfo in preloaded-classes
Without this, boot fails with:

12-05 21:06:56.984: ERROR/Zygote(435):
java.lang.IllegalStateException: Missing class(es) for preloading,
update preloaded-classes [android.server.search.SearchableInfo]

This was caused by https://android-git.corp.google.com/g/34797

Change-Id: I195b7e72a411401e2de8c1d6c2e7db0fe1badec6